name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install root dependencies
        run: npm ci
        working-directory: ./
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend
      - name: Testing
        run: npm test
        working-directory: ./
        env:
          CI: true
      - name: Install codecov
        run: npm install -g codecov
        working-directory: ./
      - name: Codecov
        run: npm run codecov
        working-directory: ./
        env:
          CI: true
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
