name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'          
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            backend/package-lock.json
            frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Building release
        run: npm run buildbinary
      - name: Get the version
        id: get_version
        run: |
          TAG_NAME=${{github.ref_name}}
          echo ::set-output name=VERSION::${TAG_NAME//./_}
      - name: Archiving binaries
        run: |
          zip ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-win-x64.zip ci-traffic-light-win.exe
          tar -cvzf ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-linux-x64.tar.gz ci-traffic-light-linux
          zip ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-macos-x64.zip ci-traffic-light-macos
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-win-x64.zip
            ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-linux-x64.tar.gz
            ci-traffic-light-${{ steps.get_version.outputs.VERSION }}-macos-x64.zip
          draft: true
          body_path: CHANGELOG.md
