name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Building release
        run: npm run buildbinary
      - name: Get the version
        id: get_version
        run: |
          TAG_NAME=${{github.ref_name}}
          echo ::set-output name=VERSION::${TAG_NAME//./_}
      - name: Adding tagname to binaries
        run: |
          mv ci-traffic-light-win.exe ci-traffic-light-win-${{ steps.get_version.outputs.VERSION }}.exe
          mv ci-traffic-light-linux ci-traffic-light-linux-${{ steps.get_version.outputs.VERSION }} 
          mv ci-traffic-light-macos ci-traffic-light-macos-${{ steps.get_version.outputs.VERSION }}
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ci-traffic-light-win-${{ steps.get_version.outputs.VERSION }}.exe
            ci-traffic-light-linux-${{ steps.get_version.outputs.VERSION }}
            ci-traffic-light-macos-${{ steps.get_version.outputs.VERSION }}
          draft: true
          body_path: CHANGELOG.md
